//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UttGameSessionService.ServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameSessionMoveDto", Namespace="http://schemas.datacontract.org/2004/07/GameService")]
    [System.SerializableAttribute()]
    public partial class GameSessionMoveDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BigCellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCrossField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BigCell {
            get {
                return this.BigCellField;
            }
            set {
                if ((this.BigCellField.Equals(value) != true)) {
                    this.BigCellField = value;
                    this.RaisePropertyChanged("BigCell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCross {
            get {
                return this.IsCrossField;
            }
            set {
                if ((this.IsCrossField.Equals(value) != true)) {
                    this.IsCrossField = value;
                    this.RaisePropertyChanged("IsCross");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Position {
            get {
                return this.PositionField;
            }
            set {
                if ((this.PositionField.Equals(value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.IGameSessionService", CallbackContract=typeof(UttGameSessionService.ServiceRef.IGameSessionServiceCallback))]
    public interface IGameSessionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameSessionService/SetupSession", ReplyAction="http://tempuri.org/IGameSessionService/SetupSessionResponse")]
        void SetupSession(string username, string opponentUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameSessionService/SetupSession", ReplyAction="http://tempuri.org/IGameSessionService/SetupSessionResponse")]
        System.Threading.Tasks.Task SetupSessionAsync(string username, string opponentUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameSessionService/Step", ReplyAction="http://tempuri.org/IGameSessionService/StepResponse")]
        void Step(int bigCell, int position);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameSessionService/Step", ReplyAction="http://tempuri.org/IGameSessionService/StepResponse")]
        System.Threading.Tasks.Task StepAsync(int bigCell, int position);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameSessionService/Sync", ReplyAction="http://tempuri.org/IGameSessionService/SyncResponse")]
        UttGameSessionService.ServiceRef.GameSessionMoveDto[] Sync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameSessionService/Sync", ReplyAction="http://tempuri.org/IGameSessionService/SyncResponse")]
        System.Threading.Tasks.Task<UttGameSessionService.ServiceRef.GameSessionMoveDto[]> SyncAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameSessionServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameSessionService/SendStep", ReplyAction="http://tempuri.org/IGameSessionService/SendStepResponse")]
        void SendStep(UttGameSessionService.ServiceRef.GameSessionMoveDto move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameSessionService/SyncRoles", ReplyAction="http://tempuri.org/IGameSessionService/SyncRolesResponse")]
        void SyncRoles(bool isCross);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameSessionServiceChannel : UttGameSessionService.ServiceRef.IGameSessionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameSessionServiceClient : System.ServiceModel.DuplexClientBase<UttGameSessionService.ServiceRef.IGameSessionService>, UttGameSessionService.ServiceRef.IGameSessionService {
        
        public GameSessionServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameSessionServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameSessionServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameSessionServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameSessionServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SetupSession(string username, string opponentUsername) {
            base.Channel.SetupSession(username, opponentUsername);
        }
        
        public System.Threading.Tasks.Task SetupSessionAsync(string username, string opponentUsername) {
            return base.Channel.SetupSessionAsync(username, opponentUsername);
        }
        
        public void Step(int bigCell, int position) {
            base.Channel.Step(bigCell, position);
        }
        
        public System.Threading.Tasks.Task StepAsync(int bigCell, int position) {
            return base.Channel.StepAsync(bigCell, position);
        }
        
        public UttGameSessionService.ServiceRef.GameSessionMoveDto[] Sync() {
            return base.Channel.Sync();
        }
        
        public System.Threading.Tasks.Task<UttGameSessionService.ServiceRef.GameSessionMoveDto[]> SyncAsync() {
            return base.Channel.SyncAsync();
        }
    }
}
