//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExternalServices.MatchMaker {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatchMaker.IMatchMakerService", CallbackContract=typeof(ExternalServices.MatchMaker.IMatchMakerServiceCallback))]
    public interface IMatchMakerService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchMakerService/Enqueue")]
        void Enqueue(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchMakerService/Enqueue")]
        System.Threading.Tasks.Task EnqueueAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchMakerService/Dequeue")]
        void Dequeue(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchMakerService/Dequeue")]
        System.Threading.Tasks.Task DequeueAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchMakerServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchMakerService/MatchFound")]
        void MatchFound(string opponentUsername);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchMakerServiceChannel : ExternalServices.MatchMaker.IMatchMakerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchMakerServiceClient : System.ServiceModel.DuplexClientBase<ExternalServices.MatchMaker.IMatchMakerService>, ExternalServices.MatchMaker.IMatchMakerService {
        
        public MatchMakerServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MatchMakerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MatchMakerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchMakerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchMakerServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Enqueue(string username) {
            base.Channel.Enqueue(username);
        }
        
        public System.Threading.Tasks.Task EnqueueAsync(string username) {
            return base.Channel.EnqueueAsync(username);
        }
        
        public void Dequeue(string username) {
            base.Channel.Dequeue(username);
        }
        
        public System.Threading.Tasks.Task DequeueAsync(string username) {
            return base.Channel.DequeueAsync(username);
        }
    }
}
